### ISSUE TITLE
Setup logging and add relevant logs on main operations

### ISSUE THREAD

**Issue by comoser** [comoser/baby-food-intro-api#12]
The API is currently feature-ready for MVP, BUT there's a very important piece missing. There's no logs!

We need to implement logging in the application so that we can later monitor.

This ticket also assumes we go through the main operations of the API and add logging there (there aren't many operations on the API, so it's doable in a single PR)

**Comment by VitorFernandes2** [comment]
Hi @comoser, can I take this one?

**Comment by comoser** [comment]
> Hi @comoser, can I take this one?

Hey! For sure. I’ll assign the issue to you
